# Generated by Django 5.2.4 on 2025-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('joke', models.TextField(verbose_name='Анекдот')),
                ('votes', models.IntegerField(verbose_name='Голоса')),
            ],
        ),
    ]
