# Generated by Django 5.2.4 on 2025-07-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={'verbose_name': 'Анекдот', 'verbose_name_plural': 'Анекдоты'},
        ),
        migrations.AlterField(
            model_name='joke',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
    ]
